name: Build (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}
  
    steps:
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config

      - name: SDL2 Checkout
        uses: actions/checkout@v4
        with:
          repository: libsdl-org/SDL
          ref: release-2.30.x
          path: sdl2
      
      - name: SDL2 Configure
        working-directory: ./sdl2
        run: |
          cmake -B build -G Ninja -DCMAKE_C_FLAGS=-mwindows -DCMAKE_BUILD_TYPE=Release -DSDL_STATIC=ON -DSDL_SHARED=OFF
      
      - name: SDL2 Build
        working-directory: ./sdl2
        run: |
          cmake --build build --config Release
      
      - name: SDL2 Install
        working-directory: ./sdl2
        run: |
          cmake --install build --config Release
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      
      - name: Configure
        working-directory: ./main
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      
      - name: Build
        working-directory: ./main
        run: |
          cmake --build build
      
      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          path: main/build/sdl2-hello.exe
